#!/bin/bash
REPO_PATH="$(realpath "$(dirname "${BASH_SOURCE[0]}")/../..")"

echo "Building @ $REPO_PATH"

: "${DOCKER_REPOSITORY:="docker.io/lamaani/stratis"}"

if [ -n "$DOCKER_PASSWORD" ]; then
    echo "Docker logging in $DOCKER_USERNAME"
    docker login -p "$DOCKER_PASSWORD" -u "$DOCKER_USERNAME" "$DOCKER_REPOSITORY" || exit $?
fi

: "${IMAGE_TAGS:="local"}"
TAGS=($IMAGE_TAGS)


IMAGE_NAMES=()
for tag in "${TAGS[@]}"; do
    IMAGE_NAMES+=("$DOCKER_REPOSITORY:${tag}")
done

docker build -t "${IMAGE_NAMES[0]}" -f "$REPO_PATH/docker/nodejs/Dockerfile" "$REPO_PATH" || exit $?
for name in "${IMAGE_NAMES[@]}"; do
    docker tag "${IMAGE_NAMES[0]}" "${name}"
    docker push "$name"
done

