#!/bin/bash
REPO_PATH="$(realpath "$(dirname "${BASH_SOURCE[0]}")/../..")"

echo "Building @ $REPO_PATH"

: "${DOCKER_REPOSITORY:="docker.io/lamaani/stratis"}"

if [ -n "$DOCKER_PASSWORD" ]; then
    echo "Docker logging in $DOCKER_USERNAME"
    echo "$DOCKER_PASSWORD" | docker login --password-stdin -u "$DOCKER_USERNAME" || exit $?
fi

: "${IMAGE_TAGS:="local"}"
TAGS=($IMAGE_TAGS)


IMAGE_NAMES=()
for tag in "${TAGS[@]}"; do
    IMAGE_NAMES+=("$DOCKER_REPOSITORY:${tag}")
done

docker build -t "${IMAGE_NAMES[0]}" -f "$REPO_PATH/docker/Dockerfile" "$REPO_PATH" || exit $?
for name in "${IMAGE_NAMES[@]}"; do
    docker tag "${IMAGE_NAMES[0]}" "${name}" || exit $?
    docker push "$name" || exit $?
    echo "Pushed: $name"
done

