#!/bin/bash
source zbash_commons

if [ "$ENABLE_GIT_AUTOSYNC" == "true" ]; then
    log:sep "Autosync"
    git_autosync --async
    assert $? "Faild to start autosync" || exit $?
fi

[ -n "$STRATIS_SERVE_PATH" ]
assert $? "Invalid serve path: $STRATIS_SERVE_PATH"

log:sep "Starting stratis web server"
stratis "$STRATIS_SERVE_PATH"

